diff a/Dockerfile b/Dockerfile	(rejected hunks)
@@ -1,9 +1,12 @@
 FROM continuumio/miniconda3
 
-COPY . /srv
+WORKDIR /src/cads-processing-api-service
 
-WORKDIR /srv
+COPY environment.yml /src/cads-processing-api-service/
 
-RUN conda install -c conda-forge make gcc python=3.10 \
-    && make conda-env-update CONDAFLAGS="-n base" \
-    && pip install -e .
+RUN conda install -c conda-forge gcc python=3.10 \
+    && conda env update -n base -f environment.yml
+
+COPY . /src/cads-processing-api-service
+
+RUN pip install --no-deps -e .
