channels:
- conda-forge
- nodefaults
dependencies:
- fastapi
- make
- mypy
- pip
- pre-commit
- pytest
- pytest-cov
- python>=3.10
- sqlalchemy
- sqlalchemy-stubs
- uvicorn
- pip:
  - fastapi-utils
  - git+https://github.com/ecmwf-projects/ogc-api-processes-fastapi.git
